[phases.setup]
nixpkgs = ["python3", "postgresql_16.dev", "gcc"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv", ". /opt/venv/bin/activate", "pip install -r ecommerce_project/requirements.txt"]

[start]
cmd = "uvicorn app.main:app --host=0.0.0.0 --port=${PORT:-8000}"
